name: geo-spatial-one
channels:
- conda-forge
dependencies:
- altair
- basemap
- animatplot
- bokeh
- cairo 
- cartopy
- cfgrib
- cmaps
- cmasher
- cmcrameri
- cmocean
- colorcet
- datashader
- descartes
- eccodes
- ecmwf-api-client
- esmf
- fiona
- folium
- geemap
- geopandas
- geoplot
- geoviews
- holoviews
- hvplot
- imageio-ffmpeg
- intake
- intake-xarray
- ipywidgets
- iris
- iris-grib
- iris-sample-data
- jupyter
- jupyterlab
- keras
- mayavi
- metpy
- matplotlib
- matplotlib-base
- matplotlib-scalebar
- notebook
- palettable
- pandas
- pygrib
- python>=3.9
- pyvista
- rasterio
- rioxarray
- seaborn
- salem
- shapely
- vega_datasets
- viscm
- vispy
- windrose
- xagg
- xarray
- xarray_leaflet
- pip:
  - imdlib

